name: Build wheels

on: [push, pull_request]

jobs:
  unix:
    name: ${{ matrix.os }} | ${{ matrix.arch }} | ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, macos-15]
        arch: [auto, aarch64]
        python: [cp37-*, cp38-*, cp39-*, cp310-*, cp311-*, cp312-*]
        include:
          - os: macos-14
            macos_deployment_target: 14
          - os: macos-15
            macos_deployment_target: 15
        exclude:
          - os: macos-14
            arch: aarch64
          - os: macos-14
            python: cp37-*
          - os: macos-15
            arch: aarch64
          - os: macos-15
            python: cp37-*

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos_deployment_target }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.python }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
