name: Build wheels

on: [push, pull_request]

jobs:
  windows-msvc:
    name: ${{ matrix.runner }} | ${{ matrix.python }}
    runs-on: ${{ matrix.runner }}
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg-cache
    strategy:
      fail-fast: false
      matrix:
        python: [cp39-*]
        runner: [windows-2022, windows-11-arm]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{github.workspace}}\vcpkg-cache
          key: ${{ hashFiles('vcpkg.json') }}-${{ matrix.runner }}-vcpkg-wheel-cache
          restore-keys: ${{ matrix.runner }}-vcpkg-wheel-cache

      - name: Create cache directory
        run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}} -Force

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: ${{ matrix.python }}
          SKBUILD_CMAKE_ARGS: "--preset=vcpkg-vs-github"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
