name: check_man_pages

on: [push, pull_request]

jobs:
  generate_man_pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt install help2man libglib2.0-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build ${{env.CMAKE_FLAGS}} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Generate man pages
        run: ${{github.workspace}}/docs/generate_man_pages.sh

      - name: Check result
        run: git diff --exit-code
