name: test

on: [push, pull_request]

env:
  CMAKE_FLAGS: -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror"

jobs:

  windows_msvc:
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg-cache
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2022, windows-11-arm]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ${{github.workspace}}\vcpkg-cache
        key: ${{ hashFiles('vcpkg.json') }}-${{ matrix.runner }}-vcpkg-cache
        restore-keys: ${{ matrix.runner }}-vcpkg-cache

    - name: Create cache directory
      run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}} -Force

    # Builds dependencies using vcpkg, leveraging cache
    - name: Run CMake
      run: cmake --preset=vcpkg-vs-github

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --output-on-failure --test-dir build -C Release
