name: test

on: [push, pull_request]

env:
  CMAKE_FLAGS: -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror"

jobs:

  macos:
    strategy:
      matrix:
        os: [macos-14, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install lua

    - name: Debug
      run : |
        set -xe
        cmake --version
        env

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{env.CMAKE_FLAGS}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: sudo ctest --output-on-failure

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Build C Example
      working-directory: ${{github.workspace}}/examples/c
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

    - name: Build C++ Example
      working-directory: ${{github.workspace}}/examples/cpp
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

    - name: Build and Run C++ Log Writer Example
      working-directory: ${{github.workspace}}/examples/cpp/lcm_log_writer
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build
        build/lcm_log_writer build/example.log
